"""Local operational state, stored in a single SQLite file.

The persistence layer only: schema creation, schema versioning and a small
explicit v1 -> v2 -> v3 -> v4 migration path, WAL journalling, enforced foreign
keys, transactional writes, and a set of durable operational records -
strategy runs, signals, risk events, system events, local position snapshots,
order intents, broker-order snapshots, the (schema v3) UTC-day risk baselines
the crypto daily-loss halt measures against, and the (schema v4) reconciliation
runs and events that record what crash recovery concluded.

Quantities are exact `decimal.Decimal` values, stored as canonical decimal
text: crypto positions are fractional, and a binary float cannot hold one
exactly.

Nothing here trades, and nothing here reconciles. Storing an order intent is
not placing an order, and storing a reconciliation run is not performing one:
this package contacts no broker, holds no credentials, and opens no socket.
`autotrader.reconciliation` decides what broker truth is and hands the
conclusion here to be written down. There is still no fill, execution, or
broker-account table. See docs/SPEC.md section 8.
"""

from autotrader.state.sqlite import (
    BUSY_TIMEOUT_MS,
    DEFAULT_DATABASE_PATH,
    INTENT_STATUS_CONFIRMED_NOT_SUBMITTED,
    INTENT_STATUS_CREATED,
    INTENT_STATUS_REJECTED,
    INTENT_STATUS_SUBMITTED,
    INTENT_STATUS_SUBMITTING,
    INTENT_STATUS_UNKNOWN,
    MIN_MIGRATABLE_SCHEMA_VERSION,
    ORDER_INTENT_STATUSES,
    ORDER_SIDES,
    RECONCILIATION_CATEGORIES,
    RECONCILIATION_OUTCOMES,
    RECONCILIATION_STATUS_CLEAN,
    RECONCILIATION_STATUS_FAILED,
    RECONCILIATION_STATUS_REPAIRED,
    RECONCILIATION_STATUS_UNRESOLVED,
    RECONCILIATION_STATUSES,
    REQUIRED_TABLES,
    RUN_MODES,
    RUN_STATUS_COMPLETED,
    RUN_STATUS_FAILED,
    RUN_STATUS_RUNNING,
    RUN_STATUSES,
    SCHEMA_VERSION,
    SIGNAL_TYPES,
    TERMINAL_INTENT_STATUSES,
    TERMINAL_RUN_STATUSES,
    TIMESTAMP_FORMAT,
    V2_TABLES,
    V3_TABLES,
    V4_TABLES,
    DailyRiskBaseline,
    DatabaseStateError,
    DuplicateBrokerOrderError,
    DuplicateOrderIntentError,
    DuplicateSignalError,
    Position,
    ReconciliationEvent,
    ReconciliationRun,
    RiskEvent,
    StateError,
    StateInputError,
    StoredBrokerOrder,
    StoredOrderIntent,
    StoredSignal,
    StrategyRun,
    SystemEvent,
    UnknownOrderIntentError,
    UnknownReconciliationRunError,
    UnknownStrategyRunError,
    UnsupportedSchemaVersionError,
    connect,
    ensure_daily_risk_baseline,
    finish_strategy_run,
    from_decimal_text,
    from_risk_date_text,
    from_utc_text,
    get_broker_order_by_client_id,
    get_broker_order_by_intent,
    get_daily_risk_baseline,
    get_order_intent,
    get_order_intent_by_client_id,
    get_position,
    get_reconciliation_run,
    get_schema_version,
    get_strategy_run,
    initialize_database,
    latest_reconciliation_run,
    list_broker_orders,
    list_daily_risk_baselines,
    list_order_intents,
    list_positions,
    list_reconciliation_events,
    list_reconciliation_runs,
    list_risk_events,
    list_signals,
    list_strategy_runs,
    list_system_events,
    record_order_intent,
    record_reconciliation_event,
    record_reconciliation_run,
    record_risk_event,
    record_signal,
    record_strategy_run,
    record_system_event,
    to_decimal_text,
    to_risk_date_text,
    to_utc_text,
    transaction,
    update_order_intent_status,
    upsert_broker_order,
    upsert_position,
    utc_risk_date,
)

__all__ = [
    "BUSY_TIMEOUT_MS",
    "DEFAULT_DATABASE_PATH",
    "INTENT_STATUS_CONFIRMED_NOT_SUBMITTED",
    "INTENT_STATUS_CREATED",
    "INTENT_STATUS_REJECTED",
    "INTENT_STATUS_SUBMITTED",
    "INTENT_STATUS_SUBMITTING",
    "INTENT_STATUS_UNKNOWN",
    "MIN_MIGRATABLE_SCHEMA_VERSION",
    "ORDER_INTENT_STATUSES",
    "ORDER_SIDES",
    "RECONCILIATION_CATEGORIES",
    "RECONCILIATION_OUTCOMES",
    "RECONCILIATION_STATUSES",
    "RECONCILIATION_STATUS_CLEAN",
    "RECONCILIATION_STATUS_FAILED",
    "RECONCILIATION_STATUS_REPAIRED",
    "RECONCILIATION_STATUS_UNRESOLVED",
    "REQUIRED_TABLES",
    "RUN_MODES",
    "RUN_STATUSES",
    "RUN_STATUS_COMPLETED",
    "RUN_STATUS_FAILED",
    "RUN_STATUS_RUNNING",
    "SCHEMA_VERSION",
    "SIGNAL_TYPES",
    "TERMINAL_INTENT_STATUSES",
    "TERMINAL_RUN_STATUSES",
    "TIMESTAMP_FORMAT",
    "V2_TABLES",
    "V3_TABLES",
    "V4_TABLES",
    "DailyRiskBaseline",
    "DatabaseStateError",
    "DuplicateBrokerOrderError",
    "DuplicateOrderIntentError",
    "DuplicateSignalError",
    "Position",
    "ReconciliationEvent",
    "ReconciliationRun",
    "RiskEvent",
    "StateError",
    "StateInputError",
    "StoredBrokerOrder",
    "StoredOrderIntent",
    "StoredSignal",
    "StrategyRun",
    "SystemEvent",
    "UnknownOrderIntentError",
    "UnknownReconciliationRunError",
    "UnknownStrategyRunError",
    "UnsupportedSchemaVersionError",
    "connect",
    "ensure_daily_risk_baseline",
    "finish_strategy_run",
    "from_decimal_text",
    "from_risk_date_text",
    "from_utc_text",
    "get_broker_order_by_client_id",
    "get_broker_order_by_intent",
    "get_daily_risk_baseline",
    "get_order_intent",
    "get_order_intent_by_client_id",
    "get_position",
    "get_reconciliation_run",
    "get_schema_version",
    "get_strategy_run",
    "initialize_database",
    "latest_reconciliation_run",
    "list_broker_orders",
    "list_daily_risk_baselines",
    "list_order_intents",
    "list_positions",
    "list_reconciliation_events",
    "list_reconciliation_runs",
    "list_risk_events",
    "list_signals",
    "list_strategy_runs",
    "list_system_events",
    "record_order_intent",
    "record_reconciliation_event",
    "record_reconciliation_run",
    "record_risk_event",
    "record_signal",
    "record_strategy_run",
    "record_system_event",
    "to_decimal_text",
    "to_risk_date_text",
    "to_utc_text",
    "transaction",
    "update_order_intent_status",
    "upsert_broker_order",
    "upsert_position",
    "utc_risk_date",
]
