"""Local operational state, stored in a single SQLite file.

The persistence layer only: schema creation, schema versioning and one small
explicit v1 -> v2 migration, WAL journalling, enforced foreign keys,
transactional writes, and a set of durable operational records - strategy
runs, signals, risk events, system events, local position snapshots, and
(schema v2, Phase 7) order intents and broker-order snapshots.

Nothing here trades. Storing an order intent is not placing an order: this
package contacts no broker, holds no credentials, and opens no socket. There
is still no fill, execution, or reconciliation table - Phase 8 owns that
vocabulary. See docs/SPEC.md section 8.
"""

from autotrader.state.sqlite import (
    BUSY_TIMEOUT_MS,
    DEFAULT_DATABASE_PATH,
    INTENT_STATUS_CREATED,
    INTENT_STATUS_REJECTED,
    INTENT_STATUS_SUBMITTED,
    INTENT_STATUS_SUBMITTING,
    INTENT_STATUS_UNKNOWN,
    MIN_MIGRATABLE_SCHEMA_VERSION,
    ORDER_INTENT_STATUSES,
    ORDER_SIDES,
    REQUIRED_TABLES,
    RUN_MODES,
    RUN_STATUS_COMPLETED,
    RUN_STATUS_FAILED,
    RUN_STATUS_RUNNING,
    RUN_STATUSES,
    SCHEMA_VERSION,
    SIGNAL_TYPES,
    TERMINAL_RUN_STATUSES,
    TIMESTAMP_FORMAT,
    V2_TABLES,
    DatabaseStateError,
    DuplicateBrokerOrderError,
    DuplicateOrderIntentError,
    DuplicateSignalError,
    Position,
    RiskEvent,
    StateError,
    StateInputError,
    StoredBrokerOrder,
    StoredOrderIntent,
    StoredSignal,
    StrategyRun,
    SystemEvent,
    UnknownOrderIntentError,
    UnknownStrategyRunError,
    UnsupportedSchemaVersionError,
    connect,
    finish_strategy_run,
    from_utc_text,
    get_broker_order_by_client_id,
    get_broker_order_by_intent,
    get_order_intent,
    get_order_intent_by_client_id,
    get_position,
    get_schema_version,
    get_strategy_run,
    initialize_database,
    list_broker_orders,
    list_order_intents,
    list_positions,
    list_risk_events,
    list_signals,
    list_strategy_runs,
    list_system_events,
    record_order_intent,
    record_risk_event,
    record_signal,
    record_strategy_run,
    record_system_event,
    to_utc_text,
    transaction,
    update_order_intent_status,
    upsert_broker_order,
    upsert_position,
)

__all__ = [
    "BUSY_TIMEOUT_MS",
    "DEFAULT_DATABASE_PATH",
    "INTENT_STATUS_CREATED",
    "INTENT_STATUS_REJECTED",
    "INTENT_STATUS_SUBMITTED",
    "INTENT_STATUS_SUBMITTING",
    "INTENT_STATUS_UNKNOWN",
    "MIN_MIGRATABLE_SCHEMA_VERSION",
    "ORDER_INTENT_STATUSES",
    "ORDER_SIDES",
    "REQUIRED_TABLES",
    "RUN_MODES",
    "RUN_STATUSES",
    "RUN_STATUS_COMPLETED",
    "RUN_STATUS_FAILED",
    "RUN_STATUS_RUNNING",
    "SCHEMA_VERSION",
    "SIGNAL_TYPES",
    "TERMINAL_RUN_STATUSES",
    "TIMESTAMP_FORMAT",
    "V2_TABLES",
    "DatabaseStateError",
    "DuplicateBrokerOrderError",
    "DuplicateOrderIntentError",
    "DuplicateSignalError",
    "Position",
    "RiskEvent",
    "StateError",
    "StateInputError",
    "StoredBrokerOrder",
    "StoredOrderIntent",
    "StoredSignal",
    "StrategyRun",
    "SystemEvent",
    "UnknownOrderIntentError",
    "UnknownStrategyRunError",
    "UnsupportedSchemaVersionError",
    "connect",
    "finish_strategy_run",
    "from_utc_text",
    "get_broker_order_by_client_id",
    "get_broker_order_by_intent",
    "get_order_intent",
    "get_order_intent_by_client_id",
    "get_position",
    "get_schema_version",
    "get_strategy_run",
    "initialize_database",
    "list_broker_orders",
    "list_order_intents",
    "list_positions",
    "list_risk_events",
    "list_signals",
    "list_strategy_runs",
    "list_system_events",
    "record_order_intent",
    "record_risk_event",
    "record_signal",
    "record_strategy_run",
    "record_system_event",
    "to_utc_text",
    "transaction",
    "update_order_intent_status",
    "upsert_broker_order",
    "upsert_position",
]
