"""Local operational state, stored in a single SQLite file.

Phase 6 is the persistence foundation only: schema creation, schema
versioning, WAL journalling, enforced foreign keys, transactional writes, and
a small set of durable operational records (strategy runs, signals, risk
events, system events, and local position snapshots).

Nothing here trades. There is no broker order, fill, execution, or
reconciliation table, because Phase 7/8 own that vocabulary and guessing it
now would be worse than adding it later. See docs/SPEC.md section 8,
"Phase 6 - SQLite Operational State".
"""

from autotrader.state.sqlite import (
    BUSY_TIMEOUT_MS,
    DEFAULT_DATABASE_PATH,
    REQUIRED_TABLES,
    RUN_MODES,
    RUN_STATUS_COMPLETED,
    RUN_STATUS_FAILED,
    RUN_STATUS_RUNNING,
    RUN_STATUSES,
    SCHEMA_VERSION,
    SIGNAL_TYPES,
    TERMINAL_RUN_STATUSES,
    TIMESTAMP_FORMAT,
    DatabaseStateError,
    DuplicateSignalError,
    Position,
    RiskEvent,
    StateError,
    StateInputError,
    StoredSignal,
    StrategyRun,
    SystemEvent,
    UnknownStrategyRunError,
    UnsupportedSchemaVersionError,
    connect,
    finish_strategy_run,
    from_utc_text,
    get_position,
    get_schema_version,
    get_strategy_run,
    initialize_database,
    list_positions,
    list_risk_events,
    list_signals,
    list_strategy_runs,
    list_system_events,
    record_risk_event,
    record_signal,
    record_strategy_run,
    record_system_event,
    to_utc_text,
    transaction,
    upsert_position,
)

__all__ = [
    "BUSY_TIMEOUT_MS",
    "DEFAULT_DATABASE_PATH",
    "REQUIRED_TABLES",
    "RUN_MODES",
    "RUN_STATUSES",
    "RUN_STATUS_COMPLETED",
    "RUN_STATUS_FAILED",
    "RUN_STATUS_RUNNING",
    "SCHEMA_VERSION",
    "SIGNAL_TYPES",
    "TERMINAL_RUN_STATUSES",
    "TIMESTAMP_FORMAT",
    "DatabaseStateError",
    "DuplicateSignalError",
    "Position",
    "RiskEvent",
    "StateError",
    "StateInputError",
    "StoredSignal",
    "StrategyRun",
    "SystemEvent",
    "UnknownStrategyRunError",
    "UnsupportedSchemaVersionError",
    "connect",
    "finish_strategy_run",
    "from_utc_text",
    "get_position",
    "get_schema_version",
    "get_strategy_run",
    "initialize_database",
    "list_positions",
    "list_risk_events",
    "list_signals",
    "list_strategy_runs",
    "list_system_events",
    "record_risk_event",
    "record_signal",
    "record_strategy_run",
    "record_system_event",
    "to_utc_text",
    "transaction",
    "upsert_position",
]
